spring.application.name=backend-lab
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/backend_lab}
spring.datasource.username=${DB_USERNAME:backend_lab}
spring.datasource.password=${DB_PASSWORD:backend_lab}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=false
